_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.10.0
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 23
                - 55
                - 61
            "4": 3.10.0
            "5": 0.18.3
            "8":
                - 3
                - 5
            "12": 0.18.3
            "13": windows-amd64
